#%RAML 1.0 DataType

example: !include ../examples/singleEmpresp.json



properties:
  emp_id:
      type: string
      required: true  
  emp_name:
      type: string
      required: true
  emp_age:
      type: string
      required: true
  emp_address:
      type: string
      required: true
  emp_number:
      type: string
      required: true


